### ISSUE TITLE
Description of team members

### ISSUE THREAD

**Issue by AbelG101** [AbelG101/Ruby-capstone#20]
## Kanban board link:
- [Click here](https://github.com/AbelG101/Ruby-capstone/projects/1)
## Team members
- We are a group of 4 people
- Team member 1: @AbelG101, 
- Team member 2: @Elijahdre 
- Team member 3:  @summyalena
- Team member 4:  @Christabelle143

**Comment by codepantha** [comment]
# STATUS: APPROVED 🟢 ✔️ 

## Hi @AbelG101 @Elijahdre @summyalena 👋 , 

This milestone is complete!  You have created your Kanban board successfully and distributed tasks equally 👏 
There is nothing else to say other than... it's time to start building your project :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
